let shopItemsData = [
    {
        id: "vuhhfsgfssf",
        name: "camisa social azul",
        price: 45,
        desc: "ser chic é se sustentavel",
        img: "roupasfem/fem1.jpg",
    },
    {
        id: "mnkjhbhf",
        name: "camisa social preta",
        price: 100,
        desc: "nossa roupa tras uma paz",
        img: "roupasfem/fem2.png",
    },
    {
        id: "nbvhvgcdfx",
        name: "camisa social branca",
        price: 25,
        desc: "seja sustentavel, seja chic!",
        img: "roupasfem/fem3.png",
    },
    {
        id: "gfdsrxkjnhb",
        name: "camisa social rosa",
        price: 200,
        desc: "seja sustentavel ",
        img: "roupasfem/fem4.jpg",
    },
    {
        id: "abc",
        name: "calça verde clara",
        price: 249,
        desc: "seja Northfield",
        img: "roupasfem/fem6.jpg",
    },
    {
        id: "def",
        name: "calça verde escuro",
        price: 70,
        desc: "seja perfeita",
        img: "roupasfem/fem7.jpg",
    },
    {
        id: "ghi",
        name: "calça rosa",
        price: 80,
        desc: "seja linda ",
        img: "roupasfem/fem10.jpg",
    },
    {
        id: "ggfhgjhg",
        name:"comjunto",
        price: 50,
        desc: "seja incrivel",
        img: "roupasfem/fem11.jpg",
    },
    
    {
        id: "lnkjhjjhbb",
        name: "calça escura",
        price: 45,
        desc: "seja a melhor ",
        img: "roupasfem/fem12.jpg",
    },
    {
        id: "kjhbkjbh",
        name: "calça rosa",
        price: 100,
        desc: "seja voce mesma ",
        img: "roupasfem/fem.13.jpg",
    },
    {
        id: "kjhbkj",
        name: "vestido curto",
        price: 200,
        desc: " voce é northfield",
        img: "roupasfem/fem14.jpg",
    },
    {
        id: "kjhuifgytd",
        name: "vestido curto",
        price: 250,
        desc: "voce é a melhor",
        img: "roupasfem/fem15.jpg",
    },
    {
        id: "Um",
        name: "camisetabranca",
        price: 45,
        desc: "Camiseta branca para criança",
        img: "camisetabranca",
    },
    {
        id: "Dois",
        name: "Calça100%Linho",
        price: 100,
        desc: "Calça Leve 100% Linho",
        img: "Calça100%Linho.jpg",
    },
    {
        id: "Três",
        name: "Roupão 100% algodão para banho",
        price: 420,
        desc: "roupão para banho",
        img: "Roupão 100% algodão unissex P branco.jpg",
    },
    {
        id: "Quatro",
        name: "Camisola masculina de algodão",
        price: 152,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Camisola masculina de algodão confotavel.jpg",
    },
    {
        id: "Cinco",
        name: "Casaco Masculino Algodão",
        price: 69,
        desc: "Casaco Masculino de Algodão ",
        img: "Casaco Masculino Algodão Forrado GG-46.jpg",
    },
    {
        id: "Seis",
        name: "Camsisa xadrez em algodão",
        price: 200,
        desc: "Camisa importada masculina",
        img: "Camisa xadrez Masculna Manga curta em Algodão.jpg",
    },
    {
        id: "Sete",
        name: "Camisa Masculina Manga longa Puro Linho",
        price: 598,
        desc: "A camisa verde é confeccionado em linho",
        img: "Foxton Camisa Masculina Manga longa linho.jpg",
    },
    {
        id: "Oito",
        name: "Jaqueta Masculina Stone Azul",
        price: 479,
        desc: "A jaqueta Azul é confeccionada em sarja leve",
        img:"Jaqueta Masculina Stone Azul.jpg"
    },
    {
        id: "Nove",
        name: "Camisa Lilás Magnetada Manga Longa",
        price: 150,
        desc: "Camisa Liás Manga Longa magnetada",
        img:"Camisa lilás Magnetada Manga Longa.jpg"
    },
    {
        id: "Dez",
        name: "Casaco Masculino Fuzz Vintage",
        price: 453,
        desc: "O casco marrom é um tecido encorporado com superfície atoalhado",
        img:"Osklen Casaco Masculino Fuzz Vintage Pockets Marrom.jpg"
    },
];